export const recipes = [
  {
    id: "seafood-risotto",
    titleEn: "Gin's Seafood Risotto",
    titleJa: "ギンに捧げる海鮮リゾット",
    backstoryEn:
      "Prepared for Gin at the Baratie. A legendary dish crafted out of absolute kindness, refusing to let an enemy starve.",
    backstoryJa: "バラティエでギンのために作った、空腹の敵に差し出された伝説の人情料理。",
    ingredientsEn: [
      "Arborio rice",
      "Fresh king prawns, cleaned",
      "Squid tentacles, chopped",
      "Warm vegetable stock",
      "Minced onion",
      "Olive oil and butter",
    ],
    ingredientsJa: ["リゾット米", "新鮮なエビ", "刻んだイカ", "温かい野菜ブイヨン", "玉ねぎのみじん切り", "オリーブオイルとバター"],
    stepsEn: [
      "Soften the onion in olive oil, then stir in the dry rice.",
      "Add warm stock a ladle at a time, stirring as the rice absorbs it.",
      "Sauté the prawns and squid separately until cooked through.",
      "When the rice is tender with a slight bite, fold in the seafood and butter. Serve creamy.",
    ],
    stepsJa: [
      "オリーブオイルで玉ねぎを炒め、生米を加える。",
      "温かいブイヨンをお玉一杯ずつ加え、吸わせながら混ぜる。",
      "別のフライパンでエビとイカにしっかり火を通す。",
      "米に少し歯ごたえが残る程度に煮えたら、魚介とバターを混ぜて仕上げる。",
    ],
  },
  {
    id: "soba-noodles",
    titleEn: "Sangoro's Special Soba",
    titleJa: "サンゴロウ特製そば",
    backstoryEn:
      "Cooked undercover in the Flower Capital of Wano. The broth is so beautifully refined it created a massive, line-blocking crowd.",
    backstoryJa: "ワノ国の花の都で身を隠しながら作った、大行列を生み出した極上出汁の蕎麦。",
    ingredientsEn: [
      "Handmade buckwheat soba noodles",
      "Wano dashi broth",
      "Tempura shrimp flakes",
      "Mirin",
      "Soba dipping sauce",
    ],
    ingredientsJa: ["手打ち蕎麦", "ワノ国特製出汁", "天かす", "みりん", "濃口蕎麦つゆ"],
    stepsEn: [
      "Boil buckwheat noodles for exactly 4 minutes.",
      "Shock instantly in icy well water to keep the bite firm.",
      "Simmer the dashi broth until deep and aromatic.",
      "Serve beautifully inside a heavy traditional Wano ceramic bowl.",
    ],
    stepsJa: [
      "蕎麦を正確に4分間茹でる。",
      "すぐに冷水で締めて、コシをしっかりと残す。",
      "出汁をじっくりと煮詰め、深い香りを引き出す。",
      "ワノ国の伝統的な漆器に美しく盛り付ける。",
    ],
  },
  {
    id: "potato-paille",
    titleEn: "Early Summer Potato Paille",
    titleJa: "初夏のじゃがいものパイユ",
    backstoryEn: "A crisp snack Sanji serves aboard the Going Merry after the encounter with Aokiji, before the crew reaches Water 7.",
    backstoryJa: "青キジとの遭遇後、ウォーターセブンへ向かう途中のメリー号でサンジが振る舞った軽食。",
    ingredientsEn: ["Potatoes", "Neutral frying oil", "Salt", "Chopped parsley"],
    ingredientsJa: ["じゃがいも", "揚げ油", "塩", "刻みパセリ"],
    stepsEn: ["Cut potatoes into thin matchsticks.", "Rinse off the starch and dry thoroughly.", "Fry in small batches at 175°C until golden and crisp.", "Drain, season with salt and parsley, and serve warm."],
    stepsJa: ["じゃがいもを細い千切りにする。", "水ででんぷんを洗い流し、水気を十分に拭き取る。", "175℃の油で少量ずつ、きつね色になるまで揚げる。", "油を切り、塩とパセリを振って温かいうちに出す。"],
  },
  {
    id: "sunny-pizza",
    titleEn: "Sunny's Dinner Pizza",
    titleJa: "サニー号の夕食ピザ",
    backstoryEn: "Sanji makes pizza on the voyage to Dressrosa. Kin'emon is intrigued by this unfamiliar meal.",
    backstoryJa: "ドレスローザへの航海中、サンジが夕食に作ったピザ。見慣れない料理に錦えもんも興味津々。",
    ingredientsEn: ["Pizza dough", "Tomato sauce", "Mozzarella", "Basil", "Olive oil"],
    ingredientsJa: ["ピザ生地", "トマトソース", "モッツァレラ", "バジル", "オリーブオイル"],
    stepsEn: ["Heat the oven to 240°C with a baking tray inside.", "Stretch the dough on baking parchment.", "Spread with tomato sauce and scatter over mozzarella.", "Transfer to the hot tray and bake for 10–15 minutes until golden. Finish with basil and olive oil."],
    stepsJa: ["天板を入れたオーブンを240℃に予熱する。", "クッキングシートの上で生地を伸ばす。", "トマトソースを塗り、モッツァレラを散らす。", "熱い天板に移し、10〜15分焼く。バジルとオリーブオイルで仕上げる。"],
  },
  {
    id: "baratie-soup",
    titleEn: "Baratie Farewell Soup",
    titleJa: "バラティエの旅立ちスープ",
    backstoryEn: "Before Sanji leaves Baratie, the cooks criticize his delicious soup to help push him toward his dream.",
    backstoryJa: "サンジの旅立ちを後押しするため、バラティエのコックたちが、実はおいしいスープをわざとけなす。",
    ingredientsEn: ["Vegetable stock", "Onion", "Carrot", "Celery", "Butter", "Salt and black pepper"],
    ingredientsJa: ["野菜ブイヨン", "玉ねぎ", "にんじん", "セロリ", "バター", "塩と黒こしょう"],
    stepsEn: ["Dice the onion, carrot, and celery.", "Soften the vegetables in butter over medium heat.", "Pour in the stock and simmer until the vegetables are tender.", "Season to taste and serve. This vegetable version is a fan interpretation."],
    stepsJa: ["玉ねぎ、にんじん、セロリを角切りにする。", "中火でバターを溶かし、野菜を炒める。", "ブイヨンを注ぎ、野菜が柔らかくなるまで煮る。", "塩こしょうで味を調えて出す。この野菜スープはファンによるアレンジ。"],
  },
  {
    id: "sky-fish",
    titleEn: "Skypiea Grilled Sky Fish",
    titleJa: "空島の焼き空魚",
    backstoryEn: "In Skypiea, Sanji tries cooking sky fish and learns about their preparation from Pagaya. This version uses ordinary white fish.",
    backstoryJa: "空島で空魚の調理に挑戦し、パガヤから調理法を学ぶサンジ。ここでは普通の白身魚で再現。",
    ingredientsEn: ["White fish fillets", "Olive oil", "Lemon", "Salt and black pepper", "Fresh herbs"],
    ingredientsJa: ["白身魚の切り身", "オリーブオイル", "レモン", "塩と黒こしょう", "ハーブ"],
    stepsEn: ["Pat the fish dry and brush with olive oil.", "Season with salt, pepper, and herbs.", "Grill or pan-fry until opaque and cooked through, reaching 63°C at the center.", "Serve with lemon wedges for a taste of the White Sea."],
    stepsJa: ["魚の水気を拭き、オリーブオイルを塗る。", "塩、こしょう、ハーブで下味を付ける。", "グリルかフライパンで、中心温度63℃を目安にしっかり火を通す。", "レモンを添え、白海の気分で味わう。"],
  },
  {
    id: "whole-cake",
    titleEn: "Whole Cake Island Celebration Cake",
    titleJa: "ホールケーキアイランドのケーキ",
    backstoryEn: "Sanji, Pudding, and Chiffon make a replacement wedding cake to stop Big Mom's rampage. Sanji contributes his extraordinary Simsim Whip cream.",
    backstoryJa: "ビッグ・マムの暴走を止めるため、サンジ、プリン、シフォンが作った代わりのウェディングケーキ。サンジは極上のシムシムホイップを担当。",
    ingredientsEn: ["Ready-made chocolate sponge cake", "Cold whipping cream", "Icing sugar", "Vanilla extract", "Chocolate shavings", "Fresh strawberries"],
    ingredientsJa: ["市販のチョコスポンジ", "冷たい生クリーム", "粉砂糖", "バニラエッセンス", "削ったチョコレート", "いちご"],
    stepsEn: ["Whip the cold cream with icing sugar and vanilla to soft peaks.", "Slice the sponge into layers and spread cream between them.", "Cover with more cream and decorate with chocolate and strawberries.", "Chill until serving. This small fan version stands in for the story's giant cake and fictional cream."],
    stepsJa: ["冷たい生クリームに粉砂糖とバニラを加え、柔らかい角が立つまで泡立てる。", "スポンジを切り分け、間にクリームを塗る。", "表面にもクリームを塗り、チョコといちごで飾る。", "食べるまで冷蔵する。巨大ケーキと架空のクリームを手軽にアレンジしたファン版。"],
  },
];
